# Generated by Django 4.1.5 on 2023-01-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("starting_apis", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Locations",
            new_name="Location",
        ),
    ]
