# Generated by Django 4.1.5 on 2023-01-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmStatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.EmailField(max_length=254)),
                ("random_number", models.IntegerField(default=-1)),
                ("status", models.CharField(max_length=200)),
                ("excelSheetFile", models.FileField(null=True, upload_to="")),
            ],
        ),
    ]
