# Generated by Django 4.1.5 on 2023-01-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "algo_apis",
            "0003_remove_location_latitude_remove_location_longitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="location_name",
        ),
    ]
