# Generated by Django 4.1.5 on 2023-01-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0005_remove_rider_id_rider_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmstatusmodel",
            name="rider_to_location",
            field=models.JSONField(default={}),
        ),
    ]
