# Generated by Django 4.1.5 on 2023-01-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0007_alter_algorithmstatusmodel_rider_to_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="random_number",
            field=models.CharField(default="string", max_length=500),
        ),
        migrations.AddField(
            model_name="rider",
            name="username",
            field=models.EmailField(default="pandey7@gmail.com", max_length=254),
        ),
    ]
