# Generated by Django 4.1.5 on 2023-01-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0008_rider_random_number_rider_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rider",
            name="username",
        ),
    ]
