# Generated by Django 4.1.5 on 2023-01-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0009_remove_rider_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="username",
            field=models.EmailField(default="pandey7@gmail.com", max_length=254),
        ),
    ]
