# Generated by Django 4.1.5 on 2023-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0010_rider_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="warehouse_manager_email",
            field=models.EmailField(default="war1@gmail.com", max_length=254),
        ),
    ]
