# Generated by Django 4.1.5 on 2023-01-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0011_rider_warehouse_manager_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rider",
            name="warehouse_manager_email",
        ),
    ]
