# Generated by Django 4.1.5 on 2023-01-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0012_remove_rider_warehouse_manager_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="bag_id",
            field=models.CharField(default="-1", max_length=100),
        ),
    ]
