# Generated by Django 4.1.5 on 2023-02-06 06:13

import algo_apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0013_rider_bag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmstatusmodel",
            name="dynamicPickUpExcelSheet",
            field=models.FileField(
                null=True, upload_to=algo_apis.models.content_file_name2
            ),
        ),
    ]
