# Generated by Django 4.1.5 on 2023-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algo_apis", "0015_algorithmstatusmodel_number_of_drivers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="temp_id",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
