# Generated by Django 4.1.5 on 2023-01-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_apis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="item_volumne",
            new_name="item_volume",
        ),
        migrations.AddField(
            model_name="item",
            name="item_count",
            field=models.IntegerField(default=1),
        ),
    ]
