# Generated by Django 4.1.5 on 2023-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
                ("age", models.IntegerField()),
                ("person_type", models.CharField(max_length=100)),
                ("bike_details", models.CharField(max_length=200)),
            ],
        ),
    ]
