# Generated by Django 4.1.5 on 2023-01-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personinfo",
            name="name",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="personinfo",
            name="username",
            field=models.TextField(max_length=150),
        ),
    ]
