# Generated by Django 4.1.5 on 2023-01-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bag",
            fields=[
                ("bag_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_list", models.JSONField(default={"item": []})),
                ("bag_size", models.IntegerField(default=0)),
            ],
        ),
    ]
