# Generated by Django 4.1.5 on 2023-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
