# Generated by Django 4.1.5 on 2023-01-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0002_testing"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testing",
        ),
    ]
