# Generated by Django 4.1.5 on 2023-01-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0005_delete_testingmodule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalInfo",
        ),
    ]
