# Generated by Django 4.1.5 on 2023-01-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalInfo",
        ),
    ]
