# Generated by Django 4.1.5 on 2023-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0009_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="username",
            field=models.CharField(default="rupeshkumar", max_length=100),
            preserve_default=False,
        ),
    ]
