# Generated by Django 4.1.5 on 2023-01-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0010_personalinfo_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="username",
        ),
    ]
