# Generated by Django 4.1.5 on 2023-01-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_api", "0011_remove_personalinfo_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalInfo",
        ),
    ]
